// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"BrawlPicks/internal/ctx"
	"BrawlPicks/webserver/app"
	env "BrawlPicks/webserver/config"
	"BrawlPicks/webserver/controllers"
	"BrawlPicks/webserver/inference"
	"BrawlPicks/webserver/repositories"
	"BrawlPicks/webserver/routes"
	"BrawlPicks/webserver/scheduler"
	"BrawlPicks/webserver/services"
	"BrawlPicks/webserver/wire/providers"
)

// Injectors from app.go:

func InitializeApp(envEnv *env.Env) (*app.App, error) {
	context := ctx.GetGracefulShutdownCtx()
	swaggerRoute := providers.NewSwaggerRoute(envEnv)
	client := providers.NewHttpClient()
	mapRankingRepository := repositories.NewMapRankingRepository(envEnv)
	mapRankingDataService := services.NewMapRankingDataService(envEnv, client, mapRankingRepository)
	mapRankingController := controllers.NewMapRankingController(mapRankingDataService)
	mapRankingRoute := routes.NewMapRankingRoute(mapRankingController)
	httpClient := providers.NewInferenceHTTPClient(envEnv)
	inferenceClient := inference.NewClient(envEnv, httpClient)
	recommendationService := services.NewRecommendationService(inferenceClient)
	recommendationController := controllers.NewRecommendationController(recommendationService)
	recommendationRoute := routes.NewRecommendationRoute(recommendationController)
	mapRankingScheduler := scheduler.NewMapRankingScheduler(mapRankingDataService)
	api := providers.NewApi(envEnv, context, swaggerRoute, mapRankingRoute, recommendationRoute, mapRankingScheduler)
	appApp := app.NewApp(api)
	return appApp, nil
}

// Injectors from map_ranking.go:

func InitializeMapRankingRoute(controller *controllers.MapRankingController) *routes.MapRankingRoute {
	mapRankingRoute := routes.NewMapRankingRoute(controller)
	return mapRankingRoute
}

func InitializeMapRankingController(sv services.MapRankingDataServiceInterface) *controllers.MapRankingController {
	mapRankingController := controllers.NewMapRankingController(sv)
	return mapRankingController
}

func InitializeMapRankingService(e *env.Env, repo repositories.MapRankingRepositoryInterface) *services.MapRankingDataService {
	client := providers.NewHttpClient()
	mapRankingDataService := services.NewMapRankingDataService(e, client, repo)
	return mapRankingDataService
}

func InitializeMapRankingRepository(e *env.Env) *repositories.MapRankingRepository {
	mapRankingRepository := repositories.NewMapRankingRepository(e)
	return mapRankingRepository
}
