// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"BrawlPicks/internal/ctx"
	"BrawlPicks/scraper/app"
	env "BrawlPicks/scraper/config"
	"BrawlPicks/scraper/repositories"
	"BrawlPicks/scraper/services"
	"BrawlPicks/scraper/wire/providers"
)

// Injectors from app.go:

func InitializeApp(envEnv *env.Env) (*app.App, error) {
	context := ctx.GetGracefulShutdownCtx()
	client := providers.NewHttpClient()
	client2 := providers.NewRedisClient(envEnv)
	processedRecordRepository := repositories.NewProcessedRecordRepository(client2, envEnv)
	monitorService := services.NewMonitorService(envEnv, processedRecordRepository)
	battleLogRepository := providers.NewBattleLogRepository(envEnv)
	synergyCounterRepository, err := providers.NewSynergyCounterRepository(envEnv)
	if err != nil {
		return nil, err
	}
	scraperService := services.NewScraperService(envEnv, client, monitorService, processedRecordRepository, battleLogRepository, synergyCounterRepository)
	appApp := providers.NewScraperApp(context, scraperService, battleLogRepository, synergyCounterRepository, client2)
	return appApp, nil
}
