// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"BrawlPicks/handlers"
	"BrawlPicks/repositories"
	"BrawlPicks/services"
)

// Injectors from wire.go:

func InitializeBrawlStarsHandler(apiKey string) *handlers.BrawlStarsHandler {
	brawlStarsRepository := repositories.NewBrawlStarsRepository(apiKey)
	brawlStarsService := services.NewBrawlStarsService(brawlStarsRepository)
	brawlStarsHandler := handlers.NewBrawlStarsHandler(brawlStarsService)
	return brawlStarsHandler
}

func InitializePLHandler() *handlers.PLHandler {
	plRepository := repositories.NewPLRepository()
	plService := services.NewPLService(plRepository)
	plHandler := handlers.NewPLHandler(plService)
	return plHandler
}
